service: product-service
frameworkVersion: '3'
configValidationMode: warn

provider:
  name: aws
  deploymentMethod: direct
  runtime: nodejs16.x
  stage: dev
  region: eu-central-1
  tracing:
    lambda: true

package:
  individually: true

plugins:
  - serverless-webpack

functions:
  getProductsList:
    handler: lambdas/getProductsList.handler
    events:
      - http:
          path: products 
          method: get
          cors: true
  
  getProductsById:
    handler: lambdas/getProductsById.handler
    events:
      - http:
          path: products/{productId}
          method: get
          cors: true